Working starting point for FL
aidotse/LeakPro pull request #159
Opened 2024-10-11 14:25 UTC by viktorvaladi

Rough starting point that needs some more work for FL. The attack is working here and moved to example/ with some refactoring / additions on functionality

2024-10-22 09:37 UTC, mattiasakesson commented on examples/gia/cifar100_inverting_16_images/model.py
can't we have models in a subdirectory under examples to get rid of duplications?

2024-10-22 09:38 UTC, mattiasakesson commented on examples/gia/cifar10_inverting_1_image/cifar.py
can't we have dataset in a subdirectory under examples to get rid of duplications for every example?

2024-10-22 09:57 UTC, mattiasakesson commented on leakpro/attacks/gia_attacks/invertinggradients.py
maybe add the individual settings in init for class InvertingGradients?

2024-10-22 09:58 UTC, mattiasakesson requested changes
I added some design questions, but overall everything looks good.

2024-10-22 11:15 UTC, viktorvaladi commented on leakpro/attacks/gia_attacks/invertinggradients.py
Could you elaborate?

2024-10-22 11:19 UTC, viktorvaladi commented on examples/gia/cifar100_inverting_16_images/model.py
A good point, but I would argue that for transparency it's better to have each example completely standalone with as few dependencies to our framework as possible. So each example folder should clearly present the parts that we expect a user to supply to run LeakPro. I think in this case repetition of code is OK

2024-10-22 11:19 UTC, viktorvaladi commented on examples/gia/cifar10_inverting_1_image/cifar.py
Same as above (and also the cifars vary a bit in their implementation)

2024-10-22 12:05 UTC, mattiasakesson commented on leakpro/attacks/gia_attacks/invertinggradients.py
like 
InvertingConfig(total_variation = 1.0e-06, attack_lr = 0.1, at_iterations = 8000, optimizer = MetaSGD(),criterion = CrossEntropyLoss(), epochs = 1):
   self.total_variation=total_variation
   ...
then you could have the possibility to build the object in one line:
InvertingConfig(kvarg)

2024-10-22 12:44 UTC, viktorvaladi commented on leakpro/attacks/gia_attacks/invertinggradients.py
Good point. I pushed adding types to the config. Then the @dataclass decorator handles the rest, so now we can initialize it like this:
`config = InvertingConfig(total_variation = 1.0e-04)`
:)

2024-10-25 11:39 UTC, mattiasakesson approved these changes

2024-10-25 11:40 UTC, merged