Report handler
aidotse/LeakPro pull request #168
Opened 2024-10-29 13:45 UTC by henrikfo

# Description

Summary of changes

Adding the report handler

## Resolved Issues

- [ ] fixes #Issue

## How Has This Been Tested?

## Related Pull Requests

- #PR

2024-11-20 13:58 UTC, fazelehh requested changes
The only attack using MIAResult is LiRA. Other attacks should also use this class instead of CombinedMetric.
Some minor comments

2024-11-21 13:13 UTC, henrikfo commented on leakpro/reporting/report_handler.py
> +        self.report_dir = report_dir
This should be in the PR, there should be a function called "_try_find_rep_dir". I don't see that here either but if I open the files changed i can, do you see it there aswell?

2024-11-21 13:42 UTC, henrikfo commented on leakpro/metrics/attack_result.py
> +        self.fpr = self.fp / (self.fp + self.tn)
Yes, that's a good point

2024-11-21 13:44 UTC, henrikfo commented on leakpro/attacks/mia_attacks/lira.py
> +            assert len(self.audit_dataset["data"]) == len(self.in_members) + len(self.out_members)
Yes, I will check or create the issue and adress it in the description. Admittedly the description is sub-par, will change that.

2024-11-21 13:45 UTC, henrikfo commented on leakpro/metrics/attack_result.py
> +        # TODO REDIFINE THE CLASS SO IT DOSE NOT STORE MATRICIES BUT VECTORS
That's an old comment, will remove it

2024-12-02 15:15 UTC, gpadres approved these changes

2024-12-04 13:13 UTC, viktorvaladi approved these changes
looks good to me but check the requested changes :)

2024-12-04 13:13 UTC, viktorvaladi commented on examples/report_handler/gia_utils/cifar.py
I dont think this file is needed? Each example have their own implementation since they vary a bit.

2024-12-04 13:13 UTC, viktorvaladi commented on examples/report_handler/gia_utils/model.py
Same as above, dont think this is needed?

2024-12-10 16:54 UTC, fazelehh approved these changes

2024-12-11 14:00 UTC, henrikfo commented on examples/report_handler/gia_utils/cifar.py
Removed duplicate gia files

2024-12-11 14:00 UTC, henrikfo commented on examples/report_handler/gia_utils/model.py
Removed duplicate gia files

2024-12-11 14:01 UTC, merged