GRU model for LOS
aidotse/LeakPro pull request #170
Opened 2024-10-30 17:38 UTC by fazelehh

# Description

Summary of changes

* ... 
* ...

## Resolved Issues

- [ ] fixes #Issue

## How Has This Been Tested?

## Related Pull Requests

- #PR

2024-12-19 21:08 UTC, johanos1 requested changes

2024-12-19 21:08 UTC, johanos1 commented on examples/mia/LOS/mimic_GRUD_main.ipynb
After the attacks completed (RMIA and LiRA), I can only find the results for LIRA. What is going on here? Related to the result handler?

2024-12-20 09:47 UTC, fazelehh commented on examples/mia/LOS/ReadMe.md
> +In this use case, we focus on attacking length-of-stay classifier models. As part of the example, we train a Logistic Regression model and a Gated Recurrent Unit with Decay (GRU-D). When attacking th
I have explained how to change the audit.yaml in detail in both LR_main and GRUD_main, right before attacking the models. I can bring it here too, but I think it makes this file unnecessary too detail. What do you think?

2024-12-20 09:59 UTC, fazelehh commented on examples/mia/LOS/mimic_GRUD_main.ipynb
Both LR and GRU are calling the same function in /utils/data_processing.py. A flag is being used to determine the proper return based on whether the function is called by LR or GRU. One way to eliminate this flag is to duplicate the get_mimic_dataset() function into get_mimic_dataset_LR() and get_mimic_dataset_GRU(). However, I find this approach overly redundant. Do you have a better suggestion?

2024-12-20 10:27 UTC, fazelehh commented on examples/mia/LOS/mimic_GRUD_main.ipynb
So you don't get this pdf? 
[LeakPro_outpu5t.pdf](https://github.com/user-attachments/files/18209379/LeakPro_outpu5t.pdf)

2024-12-20 10:30 UTC, fazelehh commented on examples/mia/LOS/mimic_GRUD_main.ipynb
ok

2024-12-20 10:30 UTC, fazelehh commented on examples/mia/LOS/mimic_gru_handler.py
ok

2024-12-20 10:33 UTC, fazelehh commented on examples/mia/LOS/mimic_GRUD_main.ipynb
In the original repo I cited above this cell, they did a gird search for these parameters. The values that you can see there are the best model's values.

2024-12-20 14:05 UTC, johanos1 commented on examples/mia/LOS/ReadMe.md
> +In this use case, we focus on attacking length-of-stay classifier models. As part of the example, we train a Logistic Regression model and a Gated Recurrent Unit with Decay (GRU-D). When attacking th
I think you should remove it from up there and only have it where it is required.

2024-12-20 14:06 UTC, johanos1 commented on examples/mia/LOS/mimic_GRUD_main.ipynb
I think you can make the flag more descriptive. Use something like `use_grud = True
`

2024-12-20 14:06 UTC, johanos1 commented on examples/mia/LOS/mimic_GRUD_main.ipynb
Ok, maybe refer to the paper in the cell description and say this.

2024-12-20 14:07 UTC, johanos1 commented on examples/mia/LOS/mimic_GRUD_main.ipynb
Will you 2) to this PR?

2024-12-20 14:08 UTC, johanos1 commented on examples/mia/LOS/mimic_GRUD_main.ipynb
Nope. No PDFs at all and I could only see LiRA results

2025-01-07 10:17 UTC, fazelehh commented on examples/mia/LOS/mimic_GRUD_main.ipynb
No, it uses the early_stop_loader as the test loader. So using these 4 partitions just adds some flexibility to the user. For example, whether they want to consider data points that they used for early stopping as out-members or not ( which is the case for us at the moment)

2025-01-09 21:02 UTC, johanos1 requested changes

2025-01-09 21:02 UTC, johanos1 commented on leakpro/attacks/utils/shadow_model_handler.py
> +            shadow_model_type = self.handler.configs["shadow_model"]["model_class"]
I dont understand this snippet. If the shadow_model does not have "model_class" in the config, this will crash.

2025-01-09 21:02 UTC, johanos1 commented on examples/mia/LOS/mimic_GRUD_main.ipynb
I still get this error. It is only when the training initiates though so we can skip this...

2025-01-10 10:54 UTC, johanos1 approved these changes

2025-01-10 11:43 UTC, merged