adding celebA structure
aidotse/LeakPro pull request #175
Opened 2024-11-22 11:24 UTC by fazelehh

# Description

Summary of changes

* ... 
* ...

## Resolved Issues

- [ ] fixes #Issue

## How Has This Been Tested?

## Related Pull Requests

- #PR

2025-01-15 07:57 UTC, johanos1 requested changes

2025-01-15 07:57 UTC, johanos1 commented on examples/mia/celebA_HQ/celebA_HQ_handler.py
> +        learning_rate =0.1  # Default learning rate
these parameters are in train_config.yaml

2025-01-15 08:32 UTC, johanos1 requested changes

2025-01-15 08:32 UTC, johanos1 commented on examples/mia/celebA_HQ/celebA_HQ_handler.py
> +
Add report creation

2025-01-19 11:06 UTC, fazelehh commented on examples/mia/celebA_HQ/celebA_HQ_handler.py
> +
added

2025-01-19 11:14 UTC, johanos1 approved these changes

2025-01-19 22:54 UTC, merged